config/routes.rb
Rails.application.routes.draw do

  resources :items
  root 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :find_item, only: [:show, :edit, :update, :destory]
    
    def index
        @items = Item.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
       @item = Item.new
    end
    
    def create 
        @item = Item.new(item_params)
        if @item.save
           redirect_to root_path
        else
           render 'new'
        end
    end
    
    private 
    
    def item_params
        params.require(:item).permit(:title, :description)
    end
    
    def find_item
        @item = Item.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
    <%= f.input :title, label: "Item Title" %>
    <%= f.input :description %>
    <%= f.button :submit %>
<% end %>
    

app/views/items/index.html.erb
<% @items.each do |item| %>
    <h2><%= link_to item.title, item %></h2>
    <p><%= item.description %></p>
<% end %>

<%= link_to "New Item", new_item_path %>

app/views/items/new.html.erb
<div class="col-md-8 col-md-offset-2">
    <h1>New Page</h1></br>
    
    <%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="col-md-10 cd-md-offset-1">
    <h2><%= @item.title %></h2>
    <p><%= @item.description %></p>
    
    <div class="col-md-4 col-md-offset-4">
        <%= link_to "Back" , root_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>